#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Based on the postgres_queries_ plugin from http://samuel.github.com/python-munin/

Plugin to monitor a Fritz!Box DSL modem parameters.
"""

import sys
sys.path.append('/export/home/jmbreuer/Developer/python-munin')

from munin.fritz import MuninFritzPlugin

class MuninFritzDSLPlugin(MuninFritzPlugin):
    # args = "--base 1000"
    vlabel = "DSL analog parameters (upstream)"
    info = "DSL analog parameters (upstream)"

    field_types = (
        ('down_dslam_max', dict(
            label = "Latency (ms)",
            info = "Latency",
            type = "GAUGE",
            row = 6,
            column = 3
        )),
        ('down_dslam_min', dict(
            label = "Impulse Noise Protection",
            info = "Impulse Noise Protection",
            type = "GAUGE",
            row = 9,
            column = 3
        )),
        ('down_linecap', dict(
            label = "SNR (dB)",
            info = "Signal to Noise Ratio",
            type = "GAUGE",
            row = 12,
            column = 3
        )),
        ('down_rate', dict(
            label = "Attenuation (dB)",
            info = "Line Attenuation",
            type = "GAUGE",
            row = 13,
            column = 3
        )),
        ('down_rate', dict(
            label = "Power cutback (dB)",
            info = "Power cutback",
            type = "GAUGE",
            row = 14,
            column = 3
        )),
    )

    @property
    def title(self):
        return "Fritz!Box DSL analog upstream parameters on %s" % self.hostname

    @property
    def fields(self):
        return [
            (k, dict(
                    label = v['label'],
                    info = v['info'],
                    type = v['type'],
                    min = "0",
                )) for k, v in self.field_types]

    def execute(self):
        table = self.gettable('adsl.html')
        keys = [(k, v['row'], v['column']) for k, v in self.field_types]
        values = {}
        for k, row, column in keys:
	  values[k] = float(table[row]('td')[column].text)
	return values

if __name__ == "__main__":
    MuninFritzDSLPlugin().run()
