#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Based on the postgres_queries_ plugin from http://samuel.github.com/python-munin/

Plugin to monitor IPv4 host ping latencies
"""

import sys
sys.path.append('/export/home/jmbreuer/Developer/python-munin')

import os
import string
from munin.ping import MuninPingPlugin

class MuninPingprobePlugin(MuninPingPlugin):
    vlabel = "Ping latencies"
    info = "Ping latencies"

    @property
    def title(self):
        return "IPv4 ping latencies"

    @property
    def fields(self):
        return [
            (string.replace(e, ".", "_"), dict(
                    label = e,
                    info = e,
                    type = "GAUGE",
                    min = "0"
                )) for e in string.split(os.environ.get('ping_hosts', "localhost"), " ")]

    def execute(self):
        keys = [(host, v['info']) for host, v in self.fields]
        values = {}
        for key, host in keys:
	  p = self.getPing(host)
	  p.run(3)
	  values[key] = p.stat_avg()
	return values

if __name__ == "__main__":
    MuninPingprobePlugin().run()
