#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Based on the postgres_queries_ plugin from http://samuel.github.com/python-munin/

Plugin to monitor a Fritz!Box DSL modem parameters.
"""

import sys
sys.path.append('/export/home/jmbreuer/Developer/python-munin')

from munin.ping import MuninPingPlugin

class MuninPingprobePlugin(MuninPingPlugin):
    vlabel = "Ping latencies"
    info = "Ping latencies"

    field_types = (
        ('jb-fo_dyndns_org', dict(
            host = "jb-fo.dyndns.org",
        )),
        ('proxy_nefonline_de', dict(
            host = "proxy.nefonline.de",
        )),
        ('www_google_com', dict(
            host = "www.google.com",
        )),
    )

    @property
    def title(self):
        return "IPv4 ping latencies"

    @property
    def fields(self):
        return [
            (k, dict(
                    label = v['host'],
                    info = v['host'],
                    type = "GAUGE",
                    min = "0"
                )) for k, v in self.field_types]

    def execute(self):
        keys = [(k, v['host']) for k, v in self.field_types]
        values = {}
        for k, host in keys:
	  p = self.getPing(host)
	  p.run(3)
	  values[k] = p.stat_avg()
	return values

if __name__ == "__main__":
    MuninPingprobePlugin().run()
