#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Based on the postgres_queries_ plugin from http://samuel.github.com/python-munin/

Plugin to monitor IPv4 host ping latencies
"""

# Add our surrounding modules to the module path
import os, sys, inspect
# realpath() will make the path absolute and deal with symlinks
module_folder =  os.path.split(os.path.split(os.path.realpath(inspect.getfile(inspect.currentframe())))[0])[0]
if module_folder not in sys.path:
  sys.path.insert(0, module_folder)

import string
from munin.ping import MuninPingPlugin

class MuninPingprobePlugin(MuninPingPlugin):
    vlabel = "Ping latencies"
    info = "Ping latencies"

    @property
    def title(self):
        return "IPv4 ping latencies"

    @property
    def fields(self):
        return [
            (string.replace(e, ".", "_"), dict(
                    label = e,
                    info = e,
                    type = "GAUGE",
                    min = "0"
                )) for e in string.split(os.environ.get('ping_hosts', "localhost"), " ")]

    def execute(self):
        keys = [(host, v['info']) for host, v in self.fields]
        values = {}
        for key, host in keys:
	  p = self.getPing(host)
	  p.run(3)
	  values[key] = p.stat_avg()
	return values

if __name__ == "__main__":
    MuninPingprobePlugin().run()
